// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paxos.proto

package paxos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	B                    *Ballot  `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Kv                   *KV      `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetB() *Ballot {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Data) GetKv() *KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

type KV struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{1}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Ballot struct {
	N                    uint32   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ballot) Reset()         { *m = Ballot{} }
func (m *Ballot) String() string { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()    {}
func (*Ballot) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{2}
}

func (m *Ballot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ballot.Unmarshal(m, b)
}
func (m *Ballot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ballot.Marshal(b, m, deterministic)
}
func (m *Ballot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ballot.Merge(m, src)
}
func (m *Ballot) XXX_Size() int {
	return xxx_messageInfo_Ballot.Size(m)
}
func (m *Ballot) XXX_DiscardUnknown() {
	xxx_messageInfo_Ballot.DiscardUnknown(m)
}

var xxx_messageInfo_Ballot proto.InternalMessageInfo

func (m *Ballot) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

type Promise struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Promise) Reset()         { *m = Promise{} }
func (m *Promise) String() string { return proto.CompactTextString(m) }
func (*Promise) ProtoMessage()    {}
func (*Promise) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{3}
}

func (m *Promise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promise.Unmarshal(m, b)
}
func (m *Promise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promise.Marshal(b, m, deterministic)
}
func (m *Promise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promise.Merge(m, src)
}
func (m *Promise) XXX_Size() int {
	return xxx_messageInfo_Promise.Size(m)
}
func (m *Promise) XXX_DiscardUnknown() {
	xxx_messageInfo_Promise.DiscardUnknown(m)
}

var xxx_messageInfo_Promise proto.InternalMessageInfo

type Dummy struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{4}
}

func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (m *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(m, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Data)(nil), "paxos.Data")
	proto.RegisterType((*KV)(nil), "paxos.KV")
	proto.RegisterType((*Ballot)(nil), "paxos.Ballot")
	proto.RegisterType((*Promise)(nil), "paxos.Promise")
	proto.RegisterType((*Dummy)(nil), "paxos.Dummy")
}

func init() { proto.RegisterFile("paxos.proto", fileDescriptor_fec356ed5fe8331d) }

var fileDescriptor_fec356ed5fe8331d = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xd8, 0x4d, 0xe8, 0x24, 0x11, 0x19, 0x44, 0x6a, 0x54, 0x90, 0xf5, 0x60, 0x0f,
	0xd2, 0x43, 0xbc, 0x0b, 0x86, 0xe2, 0xa5, 0x1e, 0xc2, 0x1e, 0x2a, 0x78, 0xdb, 0xa4, 0x83, 0x84,
	0xfc, 0x25, 0x4d, 0x83, 0xf5, 0xe3, 0xf8, 0x49, 0x25, 0xbb, 0x91, 0x22, 0x48, 0x4f, 0x3b, 0x6f,
	0x7f, 0xef, 0xcd, 0xee, 0xec, 0x82, 0xdb, 0xa8, 0xcf, 0x7a, 0xbb, 0x68, 0xda, 0xba, 0xab, 0x91,
	0x6b, 0x21, 0x9e, 0x60, 0xb2, 0x54, 0x9d, 0xc2, 0x2b, 0x60, 0xc9, 0x8c, 0xdd, 0xb2, 0xb9, 0x1b,
	0xfa, 0x0b, 0xe3, 0x8b, 0x54, 0x51, 0xd4, 0x9d, 0x64, 0x09, 0x5e, 0x82, 0x95, 0xf7, 0x33, 0x4b,
	0xd3, 0xe9, 0x48, 0x57, 0x6b, 0x69, 0xe5, 0xbd, 0x78, 0x00, 0x6b, 0xb5, 0xc6, 0x33, 0x38, 0xc9,
	0x69, 0xaf, 0xf3, 0x9e, 0x1c, 0x4a, 0x3c, 0x07, 0xde, 0xab, 0x62, 0x47, 0x3a, 0xe5, 0x49, 0x23,
	0xc4, 0x05, 0xd8, 0xa6, 0x2b, 0x7a, 0xc0, 0x2a, 0xed, 0xf7, 0x25, 0xab, 0xc4, 0x14, 0x9c, 0xb8,
	0xad, 0xcb, 0x6c, 0x4b, 0xc2, 0x01, 0xbe, 0xdc, 0x95, 0xe5, 0x3e, 0xfc, 0x02, 0x1e, 0x0f, 0x27,
	0xe1, 0x7c, 0x80, 0xd4, 0xa8, 0x96, 0xf0, 0xef, 0xd5, 0x82, 0xd3, 0x51, 0x8e, 0x59, 0xbc, 0x03,
	0xfb, 0x39, 0x4d, 0xa9, 0xe9, 0xd0, 0x1d, 0xc9, 0x30, 0x5b, 0xe0, 0xfd, 0x8a, 0xa1, 0x2f, 0x0a,
	0xe0, 0xaf, 0xa4, 0xda, 0xea, 0x88, 0x27, 0x7c, 0x01, 0x47, 0x52, 0x53, 0x64, 0xa9, 0xc2, 0x6b,
	0x98, 0x48, 0x52, 0x1b, 0x3c, 0xcc, 0x1d, 0x1c, 0x4a, 0xbc, 0x01, 0xfe, 0xd6, 0x66, 0x1d, 0xfd,
	0x8f, 0xa3, 0x7b, 0xf0, 0x69, 0xf3, 0x41, 0x85, 0x4a, 0xcc, 0x5e, 0x64, 0x5e, 0x3d, 0x66, 0xef,
	0xa6, 0xf8, 0xb6, 0xcc, 0x9a, 0xd8, 0xfa, 0x53, 0x1e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x63,
	0xeb, 0x6e, 0x9f, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaxosClient is the client API for Paxos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaxosClient interface {
	Prepare(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Promise, error)
	Accept(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Dummy, error)
	Learn(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Dummy, error)
}

type paxosClient struct {
	cc *grpc.ClientConn
}

func NewPaxosClient(cc *grpc.ClientConn) PaxosClient {
	return &paxosClient{cc}
}

func (c *paxosClient) Prepare(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Promise, error) {
	out := new(Promise)
	err := c.cc.Invoke(ctx, "/paxos.Paxos/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Accept(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/paxos.Paxos/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Learn(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/paxos.Paxos/Learn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServer is the server API for Paxos service.
type PaxosServer interface {
	Prepare(context.Context, *Ballot) (*Promise, error)
	Accept(context.Context, *Data) (*Dummy, error)
	Learn(context.Context, *Data) (*Dummy, error)
}

func RegisterPaxosServer(s *grpc.Server, srv PaxosServer) {
	s.RegisterService(&_Paxos_serviceDesc, srv)
}

func _Paxos_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ballot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.Paxos/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Prepare(ctx, req.(*Ballot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.Paxos/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Accept(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Learn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Learn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.Paxos/Learn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Learn(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _Paxos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.Paxos",
	HandlerType: (*PaxosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Paxos_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Paxos_Accept_Handler,
		},
		{
			MethodName: "Learn",
			Handler:    _Paxos_Learn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}

// ReplicaClient is the client API for Replica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicaClient interface {
	Read(ctx context.Context, in *KV, opts ...grpc.CallOption) (*KV, error)
	Write(ctx context.Context, in *KV, opts ...grpc.CallOption) (*KV, error)
}

type replicaClient struct {
	cc *grpc.ClientConn
}

func NewReplicaClient(cc *grpc.ClientConn) ReplicaClient {
	return &replicaClient{cc}
}

func (c *replicaClient) Read(ctx context.Context, in *KV, opts ...grpc.CallOption) (*KV, error) {
	out := new(KV)
	err := c.cc.Invoke(ctx, "/paxos.Replica/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaClient) Write(ctx context.Context, in *KV, opts ...grpc.CallOption) (*KV, error) {
	out := new(KV)
	err := c.cc.Invoke(ctx, "/paxos.Replica/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServer is the server API for Replica service.
type ReplicaServer interface {
	Read(context.Context, *KV) (*KV, error)
	Write(context.Context, *KV) (*KV, error)
}

func RegisterReplicaServer(s *grpc.Server, srv ReplicaServer) {
	s.RegisterService(&_Replica_serviceDesc, srv)
}

func _Replica_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.Replica/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).Read(ctx, req.(*KV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replica_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.Replica/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).Write(ctx, req.(*KV))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.Replica",
	HandlerType: (*ReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Replica_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Replica_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
